### ISSUE TITLE
How to resize a vertical split window? 

### ISSUE THREAD

**Issue by shrit** [ulyssa/iamb#102]
Hi,

Is there a shortcut to resize windows after doing a `vsplit` ? 

Thanks

**Comment by ulyssa** [comment]
You can resize using the `^W-`, `^W+`, `^W<`, `^W>`, and `^W=` keybindings from Vim. There's not currently a `:resize` command like Vim has, but I filed an issue at ulyssa/modalkit#114.

**Comment by ulyssa** [comment]
I've filed an issue to update the webside documentation at ulyssa/iamb.chat#11.

**Comment by shrit** [comment]
Thanks

**Comment by shrit** [comment]
@ulyssa I have tried to use the keybinding but it did not work.
I probably think that my terminal is intercepting these bindings before iamb.
It would be great to have the `:resize` command
