### ISSUE TITLE
Thanks for this <3

### ISSUE THREAD

**Issue by ChillerDragon** [ulyssa/iamb#106]
Just wanted to thank you for this cool project! Easy and flawless to install and get started!
Smooth usage and working bug free so far!

Btw is the project name your sneaky coming out on github? xd

**Comment by ulyssa** [comment]
I'm glad you like it! :)

The project is actually named after the [metrical foot](https://en.wikipedia.org/wiki/Iamb_(poetry)) in poetry. I liked the naming scheme used in a lot of Jabber software (e.g. prosody, strophe, scansion, verse, etc.) and decided to follow suit!
