### ISSUE TITLE
Can't use "shift" + "." (qwertz) to open the command prompt

### ISSUE THREAD

**Issue by lukastriescoding** [ulyssa/iamb#109]
Hello there, I've just installed iamb on my Windows 10 Notebook and was pretty confused on not being able to use shift to type the ":". It only worked with "caps" -> "." (Qwertz layout). Pretty sure it's not a hardware problem, as I installed it in a debian environment on the same device and it worked out of the box. Hope it's not my fault, sorry if so; opening an Issue felt right :)

**Comment by ulyssa** [comment]
Thank you for reporting this! I found and fixed the issue in ulyssa/modalkit#117. I'll update iamb to use it next time I cut a new modalkit release.
