### ISSUE TITLE
Need fallback behaviour when dirs::download_dir returns None

### ISSUE THREAD

**Issue by netzego** [ulyssa/iamb#118]
```
% iamb
thread 'main' panicked at 'no dirs.downloads value configured!', src/config.rs:327:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
% uname -a
Linux sao 6.1.31-hardened1-1-hardened #1 SMP PREEMPT_DYNAMIC Thu, 01 Jun 2023 22:45:12 +0000 x86_64 GNU/Linux
% rustc --version
rustc 1.70.0 (90c541806 2023-05-31) (Arch Linux rust 1:1.70.0-1)
% iamb --version
iamb 0.0.7
```

Hope that enough info? If not let me know. Thx for your time <3

**Comment by balejk** [comment]
You can solve this by setting it in your config like this:
```json
{
	"profiles": {
        ...
	},
	"dirs": {
		"downloads": "/some/path"
	}
}
```
or by exporting the environment variable `XDG_DOWNLOAD_DIR` (see [here](https://docs.rs/dirs/latest/dirs/fn.download_dir.html)).

**Comment by netzego** [comment]
@balejk thx! Indeed, this does the trick. According to https://www.freedesktop.org/wiki/Software/xdg-user-dirs/ `$XDG_DOWNLOAD_DIR` should default to `$HOME`.

> Here is a shellscript example of how to find the desktop and the download directory: 
> `echo ${XDG_DOWNLOAD_DIR:-$HOME}`

There is an open issue from the `dirs` crate: https://github.com/xdg-rs/dirs/issues/56.

**Comment by netzego** [comment]
I opened an issue here: https://github.com/dirs-dev/dirs-rs/issues/50. But not sure if the default value should be implemented by the `dirs-rs` crate or handled by the software which pulls it in?

**Comment by benjajaja** [comment]
This should be handled somehow, the least effort would be to make it optional (and then just never download anything).

**Comment by ulyssa** [comment]
I've implemented this the way @benjajaja described, and made it optional with an error message displayed after startup when you try to download a file without either specifying a path or a downloads directory.
