### ISSUE TITLE
Remove trailing newlines in body

### ISSUE THREAD

**Issue by xethos84** [ulyssa/iamb#125]
Whenever a message is sent, a newline is appended. This breaks some functions, like interacting with Bridge bots for things like Google Chat. The bot expects the body to exactly match `command`, and fails when the body is ````command\n````. I've noticed the newline is also appended to the body of my regular messages, not just single-word ones (though it doesn't break messages in rooms as far as I've noticed).

Hopefully messages can be sent without the extraneous ````\n```` being added to every single one.

**Comment by vacuumbeef** [comment]
I'm on 0.0.8 and every message I send has an additional line in the end. I guess it's relevant to this issue?
![image](https://github.com/ulyssa/iamb/assets/51813411/70674398-febe-42f2-b2cd-aab7f2bd81c2)

**Comment by konomikitten** [comment]
I'm still having this problem, installed with cargo and on version 0.0.9. Contacts I talk to say my messages have an extra newline on the end.

**Comment by obfusk** [comment]
It seems like the newline is added by the conversion to markdown, so you'd need to trim the result of that, not its input:

```rust
use comrak::{markdown_to_html, Options};
assert_eq!(markdown_to_html("Hello, **世界**!", &Options::default()),
           "<p>Hello, <strong>世界</strong>!</p>\n");
```
