### ISSUE TITLE
Feature request: Compose messages in external editor

### ISSUE THREAD

**Issue by Fabrice-Bernes** [ulyssa/iamb#126]
Gomuks allows you to open an editor of your choice by setting the `$EDITOR` (=vim, of course) env. variable, when writing long, formatted messages. The way it works there is by opening some file `gomuks-draft-<somenumbers>.md` and sending a message with its contents on write and exit.

Can we have something similar to that? I really like like this client, and I think that using Vim to compose messages goes well with its purpose.

**Comment by ulyssa** [comment]
I could see this being useful for other editors, but I'm curious to hear what you'd like to get out of launching Vim. Are there keybindings that you use that are missing?

**Comment by Fabrice-Bernes** [comment]
> Are there keybindings that you use that are missing?

- No. All the text motions that I use work really well inside the message bar already.

I use Vim whenever I also want syntax highlighting within codeblocks, as well as highlight of spelling errors, completion menus, access to snippets and so on.

I'm sure other editors have the same features in one way or another. That's why the title of this issue is about editors in general. I mentioned vim mostly as a joke.

**Comment by jtrv** [comment]
I would like this feature as a kakoune user. I actually came here as a current gomuks user because I was hoping to see if this project had the feature since it's geared towards vim. 

This would be great for people who use other editors like kakoune, helix, etc.

**Comment by capgelka** [comment]
I also fond this feature useful for myself, so made a PR https://github.com/ulyssa/iamb/pull/155

**Comment by ulyssa** [comment]
Merged in 0565b6e.
