### ISSUE TITLE
Enable sending strikethrough text

### ISSUE THREAD

**Issue by dikey0ficial** [ulyssa/iamb#141]
Iamb doesn't support rendering of striked text nor it's sending.

# Examples

## Outcoming message

| What                    | Result         |
|:-----------------------:|:--------------:|
| Outcoming message text  | `~~qwe~~42!`   |
| Expected formatting     | ~~qwe~~42!     |
| Actual formatting       | \~\~qwe\~\~42! |

## Incoming message

| What                    | Result         |
|:-----------------------:|:--------------:|
| Incoming message text   |  ~~qwe~~42!    |
| Expected rendering      |  ~~qwe~~42!    |
| Actual rendering        |    qwe42!      |

**Comment by ulyssa** [comment]
Thank you for catching this! I didn't realize that `comrak` didn't enable it by default. I've pushed a change that enables parsing `~~` in c7864cb.

Rendering the `<del>` tag is already supported. It's possible that your terminal doesn't strikethrough, or if you're using a terminal multiplexer like `screen` that the escape sequences are getting removed.
