### ISSUE TITLE
:rooms etc. after login

### ISSUE THREAD

**Issue by aw-bib** [ulyssa/iamb#145]
Since 0.0.8 moves login to the background, as it takes some time. This is a sensible change.

However, if one fires up `imab` and issues a `:rooms` etc right away one gets an error `You did not join any room yet`.

I think it might be sensible to point out the still pending login process to the user. If one is (a bit more) patient (then me) the list will populate enventually.

**Comment by ulyssa** [comment]
I've changed the behaviour of this in #205 . All joined rooms should be present where `:rooms` expects to find them now.
