### ISSUE TITLE
IAMP fails to build under Pi OS 32bit

### ISSUE THREAD

**Issue by PeterSprague** [ulyssa/iamb#146]
IAMP fails to build under Pi OS 32bit:

----------------------------------------------------------------------------------------
The following warnings were emitted during compilation:

warning: not within a suitable 'git' worktree!
warning: VERGEN_GIT_SHA set to default

error: could not compile `iamb` (bin "iamb")

Caused by:
  process didn't exit successfully: `/home/xxx/.rustup/toolchains/stable-arm-unknown-linux-gnueabihf/bin/rustc --crate-name iamb --edition=2018 /home/xxx/.cargo/registry/src/index.crates.io-1cd66030c949c28d/iamb-0.0.8/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=151 --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=cb00e16b23192499 -C extra-filename=-cb00e16b23192499 --out-dir /tmp/cargo-install1sUktH/release/deps -L dependency=/tmp/cargo-install1sUktH/release/deps --extern arboard=/tmp/cargo-install1sUktH/release/deps/libarboard-e20cdd61df948a87.rlib --extern bitflags=/tmp/cargo-install1sUktH/release/deps/libbitflags-a8e796a846ebdf05.rlib --extern chrono=/tmp/cargo-install1sUktH/release/deps/libchrono-ffb7274ceb44d93e.rlib --extern clap=/tmp/cargo-install1sUktH/release/deps/libclap-4f969372d9b1761f.rlib --extern comrak=/tmp/cargo-install1sUktH/release/deps/libcomrak-c9c5b3467be82200.rlib --extern css_color_parser=/tmp/cargo-install1sUktH/release/deps/libcss_color_parser-9ad2127f8136abf9.rlib --extern dirs=/tmp/cargo-install1sUktH/release/deps/libdirs-89b919ee9d67327d.rlib --extern emojis=/tmp/cargo-install1sUktH/release/deps/libemojis-52741d8845064b6b.rlib --extern futures=/tmp/cargo-install1sUktH/release/deps/libfutures-7c11f414a1bc71cd.rlib --extern gethostname=/tmp/cargo-install1sUktH/release/deps/libgethostname-4a10514d9c1a8ffc.rlib --extern html5ever=/tmp/cargo-install1sUktH/release/deps/libhtml5ever-0286fca5cabb30da.rlib --extern image=/tmp/cargo-install1sUktH/release/deps/libimage-28bde26db82d94e4.rlib --extern libc=/tmp/cargo-install1sUktH/release/deps/liblibc-84717dc2e18f7b48.rlib --extern markup5ever_rcdom=/tmp/cargo-install1sUktH/release/deps/libmarkup5ever_rcdom-c22a3fe23a599b6f.rlib --extern matrix_sdk=/tmp/cargo-install1sUktH/release/deps/libmatrix_sdk-375d6a7398e93da2.rlib --extern mime=/tmp/cargo-install1sUktH/release/deps/libmime-ed45be05aa5579e5.rlib --extern mime_guess=/tmp/cargo-install1sUktH/release/deps/libmime_guess-0ecad4c74867aeed.rlib --extern modalkit=/tmp/cargo-install1sUktH/release/deps/libmodalkit-e5ff64cdbc7c6b90.rlib --extern open=/tmp/cargo-install1sUktH/release/deps/libopen-be4bcc33710c4bf3.rlib --extern regex=/tmp/cargo-install1sUktH/release/deps/libregex-55b54f79526e05fd.rlib --extern rpassword=/tmp/cargo-install1sUktH/release/deps/librpassword-247b5e49aef04117.rlib --extern serde=/tmp/cargo-install1sUktH/release/deps/libserde-696304261f3d8a26.rlib --extern serde_json=/tmp/cargo-install1sUktH/release/deps/libserde_json-5a75d4ef1497aac4.rlib --extern thiserror=/tmp/cargo-install1sUktH/release/deps/libthiserror-7c388fb5713367dc.rlib --extern tokio=/tmp/cargo-install1sUktH/release/deps/libtokio-313b628b60ef41f4.rlib --extern tracing=/tmp/cargo-install1sUktH/release/deps/libtracing-fb8ad83bc4646549.rlib --extern tracing_appender=/tmp/cargo-install1sUktH/release/deps/libtracing_appender-fb5fc88e6953affd.rlib --extern tracing_subscriber=/tmp/cargo-install1sUktH/release/deps/libtracing_subscriber-ceb925f36538870c.rlib --extern unicode_segmentation=/tmp/cargo-install1sUktH/release/deps/libunicode_segmentation-41a97d72e1ce4a9d.rlib --extern unicode_width=/tmp/cargo-install1sUktH/release/deps/libunicode_width-f995b7489e3ab714.rlib --extern url=/tmp/cargo-install1sUktH/release/deps/liburl-fd5422e8f988d223.rlib --cap-lints allow -L native=/tmp/cargo-install1sUktH/release/build/onig_sys-ec28e9731727a5d1/out -L native=/tmp/cargo-install1sUktH/release/build/ring-9aa4eeeb95bb2b66/out` (signal: 9, SIGKILL: kill)
error: failed to compile `iamb v0.0.8`, intermediate artifacts can be found at `/tmp/cargo-install1sUktH`

**Comment by ulyssa** [comment]
I'd be happy to accept PRs that make iamb compile for 32-bit, but I don't think it's likely to happen without someone putting in a lot of work chasing down and fixing the transitive dependencies preventing it from compiling.

**Comment by ulyssa** [comment]
@PeterSprague I tried cross-compiling a Linux ARMv7 binary after updating the `matrix-sdk` dependency in #200 if you want to try running that. It sounds like anything using E2EE runs much slower on ARMv7, though.
