### ISSUE TITLE
Support for threads

### ISSUE THREAD

**Issue by jcgruenhage** [ulyssa/iamb#152]
Pretty much self explanatory. Matrix has threading support, and they are fairly helpful, also when used with bots like for example in https://github.com/beeper/standupbot.

Threading is not a small task, I don't expect this to happen soon, but considering there was no issue for tracking this yet and it's not mentioned in the readme/feature comparison either, I thought I'd open an issue about it.

**Comment by ulyssa** [comment]
Done in #216 ! As mentioned in the PR, this allows you to enter a thread by pressing `<Enter>` on the thread root message. I'll eventually follow up with a `:threads` command to allow viewing the threads for a room, but I'll need to implement support for loading older messages without fetching all of the intermediate history first.
