### ISSUE TITLE
Room sorting

### ISSUE THREAD

**Issue by jcgruenhage** [ulyssa/iamb#153]
Right now, I'm absolutely at a loss after what criteria rooms are sorted in iamb, if at all. The fav'ed rooms are pinned to the top, but that seems to be about it. Having the rooms sorted at all would be nice, if this was configurable like in Element, even better.

This also related to https://github.com/ulyssa/iamb/issues/8, potentially. If I was to decide how the overview should look, I'd see a room list containing both group rooms and dm rooms, sorted by activity, with rooms that have unread messages sticking to the top and having a little indicator on them that they have unread messages.

**Comment by ulyssa** [comment]
In the current release they get sorted by tags (favorites to the top, low priority to the bottom), then by their canonical alias, then by the room identifier. I've made this customizable by several different fields in #207, and made the default for rooms sort by favorite -> low priority -> name -> room identifier instead, and room members by power level -> user id. Once I add support for unreads and mentions, then I can add `"unread"` and `"mentions"` sort fields.
