### ISSUE TITLE
Support SSO authentication

### ISSUE THREAD

**Issue by captnfab** [ulyssa/iamb#159]
Some servers (Eg. mozilla.org) only support [SSO auth](https://spec.matrix.org/latest/client-server-api/#single-sign-on), they cannot be accessed from iamb that expects password authentication.

**Comment by ulyssa** [comment]
I've merged the work that @chlohal did in #160, which should add support for OAuth and SAML, if I understand correctly what the SDK is handling. OpenID Connect will depend on updating the SDK, and doing the work to migrate from sled to sqlite (see #61).
