### ISSUE TITLE
Emoji on message bar, not working with ^N and ^P

### ISSUE THREAD

**Issue by r3k2** [ulyssa/iamb#167]
Running on Arch GNU/Linux
with Sway/Wayland.
----

So giving a try to iamb again, because I notice the sixel support PR.
according to the updated documentation:
```
From within the message bar, you can complete Matrix usernames, room aliases and identifiers, and Emoji shortcodes (e.g., :heart:) by using ^N and ^P to start cycling forwards or backwards through the list of possible completions.
```

but for emojis is not working at all, it does have work for usernames and rooms (but has other minor issues )
also tried to type for example :laught: and press enter and msg does not get converted to emoji.

PS: it does work when I do it on a :react, but not when sending msgs :/

**Comment by ulyssa** [comment]
Are you typing that final colon? If so, that won't work since it's completing a prefix. Try typing `:la` or `:laugh` and then pressing `^N`, for example.

**Comment by r3k2** [comment]
@ulyssa Thanks for the fast response :heart: works on my PC with the same OS/settings when I am back on my laptop will check to make sure I do not have another keybind on Ctrl+W+p 

Now since we at it :) I have the same issue I have try to scroll up and down the suggestions with vim hjkl or arrows with no luck, are we supposed to be able to select one of the suggestions or they are there just as a visual help? 

Thanks
PS: Cant wait for sixel support and for the e2ee be 100% implemented and I will start telling eveyrone about this great matrix client.

**Comment by r3k2** [comment]
got it to work.
