### ISSUE TITLE
linker error `status.c:(.text+0x31c): undefined reference to `curl_easy_strerror'`

### ISSUE THREAD

**Issue by hardfau18** [ulyssa/iamb#180]
iamb errors when linking with error 
```
  = note: /usr/bin/ld: /home/gireesh/gits/iamb/target/debug/deps/libsixel_sys_static-9bc14cb98e1499fc.rlib(libsixel_la-status.o): in function `sixel_helper_format_error':
          status.c:(.text+0x31c): undefined reference to `curl_easy_strerror'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `iamb` (bin "iamb") generated 1 warning
error: could not compile `iamb` (bin "iamb") due to previous error; 1 warning emitted
```

after bisecting found that it is in this 221faa828df1842abb1680b572cfb39b85289331 commit
by disabling `sixel` feature compiled it successfully

platform: Archlinux

libcurl is already present

**Comment by ulyssa** [comment]
@benjajaja Do you know what's going on here? It looks like the ` curl` feature is maybe enabled for the `sixel-sys-static` crate, but looking at `sixel-bytes` I don't think that should be the case.

**Comment by ulyssa** [comment]
@hardfau18 I've merged the fix from @benjajaja that switches to a Rust implementation instead of the C library, so you should be able to build from main now.
