### ISSUE TITLE
Wishlist: include example_config.json in release archives

### ISSUE THREAD

**Issue by tidux** [ulyssa/iamb#186]
If you're already shipping the manpages it would be nice to have a local copy of the config to start from as a base.

**Comment by aw-bib** [comment]
It might be better to point to https://github.com/ulyssa/iamb/blob/main/config.example.toml from the welcome screen and the docs.

**Comment by ulyssa** [comment]
I've included `config.example.toml` in the `.deb`, `.rpm`, `.tgz` and `.zip` files on [the v0.0.10 release page](https://github.com/ulyssa/iamb/releases/tag/v0.0.10).

**Comment by ulyssa** [comment]
Also, please note: you do not need to copy the config file as it is! The defaults are meant to be fine as they are as long as you have something under `[profiles.MYPROFILE]`. The `config.example.toml` primarily exists to show how to set non-default options.
