### ISSUE TITLE
Crash on display name with complex Unicode

### ISSUE THREAD

**Issue by kenrachynski** [ulyssa/iamb#212]
I'm using 0.0.8 via cargo.

I enabled display names and iamb immediately crashed on me with the following message:
```
thread 'main' panicked at /var/home/krachynski/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iamb-0.0.8/src/message/mod.rs:822:25:
byte index 28 is not a char boundary; it is inside 'ї' (bytes 27..29) of `🇨🇦 🏴‍☠️ Poρїŋѕҡi 🏴‍☠️ 🇨🇦 -The-Mandalorian`
```

This user has been problematic for several clients I've tried. But hey, I'll keep trying the clients.

**Comment by ulyssa** [comment]
That looks like #182 . Can you try building from main and seeing if that fixes it for you? (main does upgrade the SDK, so it will export your keys into a new session.)

**Comment by kenrachynski** [comment]
No, I'm not really interested in building the software, just using it.

**Comment by ulyssa** [comment]
The latest release, v0.0.9, includes #182. If you re-run `cargo install --locked iamb` or grab a binary from [the Releases page](https://github.com/ulyssa/iamb/releases/tag/v0.0.9) , you should no longer run into that crash.
