### ISSUE TITLE
Open room from last session after login

### ISSUE THREAD

**Issue by benjajaja** [ulyssa/iamb#24]
Store currently opened room/chat in config_dir/profiles/<server>/session.json or similar.
On startup, join the last opened room/chat from the relevant session.json.
Alternatively, configure a `default_room` in the config.json `profiles` section.

I would like to try to implement this.

**Comment by ulyssa** [comment]
I think that a `default_room` in `profiles` is a great idea! The value could then be passed to `IambWindow::find` so that it uses the same lookup logic as `gf`.

**Comment by ulyssa** [comment]
> I would like to try to implement this.

Feel free to go ahead and implement this! If you have any questions while implementing it, let me know.

**Comment by benjajaja** [comment]
done in #25
