### ISSUE TITLE
Restarting after quitting with tabs doesn't restore focus

### ISSUE THREAD

**Issue by valankar** [ulyssa/iamb#250]
I have 2 tabs:

1. DM
2. Room

In my settings I have:

```
[settings]
default_room = "room from 2 above"
```

If I am focused on tab 2, quit the app with `:qa`, and restart, it restarts focused on tab 1. I think it should restart with tab 2 focused. I'm not sure if default_room is doing anything in this case. Thanks.

**Comment by ulyssa** [comment]
Yep, this is something that should be improved. The focused tab and window information don't get worn out at the moment.

`default_room` is used when `style = "new"` in `[layout]`.

**Comment by ulyssa** [comment]
This was fixed by @Andrew-Collins in ulyssa/modalkit#143. I have updated the `modalkit-ratatui` dependency to pull it in in #319.
