### ISSUE TITLE
Cancel when replying to thread does not seem to work

### ISSUE THREAD

**Issue by valankar** [ulyssa/iamb#251]
When I select a message in the scrollback, it opens into a window of 'Replying in thread'. If I then try to `:cancel` to go back it says 'No message currently selected'. How does one cancel a thread reply? If I use `:q` it closes the whole window and I lose the chat.

**Comment by ulyssa** [comment]
You can use `<C-O>` to move backwards through the jumplist, and `<C-I>` to move forwards.

**Comment by ulyssa** [comment]
I've added a [Threads section](http://iamb.chat/messages/index.html#threads) to the documention, and mentioned that you can use `<C-O>` there.

**Comment by vimpostor** [comment]
> You can use `<C-O>` to move backwards through the jumplist, and `<C-I>` to move forwards.

I think it would still be cool to have a separate keybinding to exit the current thread and go back to the parent room, as sometimes you navigate a lot inside a thread, so you would need to hit `<C-O>` several times to go back.
