### ISSUE TITLE
<C-W>f to open room in a new tab opens it into a new window instead

### ISSUE THREAD

**Issue by valankar** [ulyssa/iamb#252]
Docs state:

```
You can also press <C-W>f while navigating a list of rooms and users to open it in a new tab instead.
```

But this seems to open a new window when I do it from `:rooms` or `:chats`. Is it a different shortcut?

**Comment by ulyssa** [comment]
Yeah, that's slightly wrong. `<C-W>f` does a split window, and `<C-W>gf` should do a new  tab.

**Comment by ulyssa** [comment]
Fixed in ulyssa/iamb.chat#23. Thank you for catching this!
