### ISSUE TITLE
`<M-[>` appears to not be working as macro

### ISSUE THREAD

**Issue by mrusme** [ulyssa/iamb#255]
I use the following config:

```toml
[macros.normal]
"<C-Q>" = ":qa<Enter>"
"<M-[>" = "gT"
"<M-]>" = "gt"
```

Pressing alt+] works flawlessly, however alt+[ does not and results in other shortcuts not working anymore until e.g. ctrl+c is being pressed.

**Comment by ulyssa** [comment]
`<M-[>` is going to appear like the start of a CSI sequence (`^[[`) in the terminal, so it's going to issues getting parsed by `crossterm` at the moment.  I believe this could be fixed enabling the [keyboard enhancement protocol](https://docs.rs/crossterm/0.27.0/crossterm/event/struct.PushKeyboardEnhancementFlags.html), which will make it work in some terminals like kitty, foot, or wezterm.

**Comment by ulyssa** [comment]
I've added support for enabling the Kitty keyboard enhancement protocol when it's available in #272, or attempting to turn on `modifyOtherKeys` when it's not. I've listed terminals that this works for over there, and I'll eventually update the website to include a Terminal Recommendations page on the site to help people find terminals with support.

**Comment by mrusme** [comment]
Just a quick follow up: Thank you for fixing this, is there going to be a new release that will include the fix anytime soon? :)

**Comment by mrusme** [comment]
I saw that a new version was released yesterday and updated. I can confirm that your fix works perfectly, `<M-[>` and `<M-]>` allow me to switch tabs now. Thank you!
