### ISSUE TITLE
Open attachments

### ISSUE THREAD

**Issue by benjajaja** [ulyssa/iamb#27]
Either a parameter to `:download`, e.g. `:download open`, or a new command `:open` that downloads and opens. "Opening" could default to `xdg-open <downloaded-file-path>` or even better have a config setting.
@ulyssa wdyt?

(I am experimenting with a new command).

**Comment by ulyssa** [comment]
I think that would be useful! There's an [`open`](https://docs.rs/open/latest/open/) crate that will take care of doing the right thing on different platforms and fallback to alternative Linux desktop commands when `xdg-open` isn't present.

I think that making a separate `:open` command that behaves like `:download` is the way to go. There's already a handful of commands for opening rooms, so I don't think that `:open` needs to be reserved for them.

I think that `MessageAction::Download` can be changed to be something like:

```rust
use bitflags::bitflags;

pub enum MessageAction {
    ...
    Download(Option<String>, DownloadFlags),
    ...
}

bitflags! {
    pub struct DownloadFlags: u32 {
        const NONE = 0b00000000;

        /// Overwrite file if it already exists.
        const FORCE = 0b00000001;

        /// Open file after downloading.
        const OPEN = 0b00000010;
    }
}
```

**Comment by benjajaja** [comment]
That sounds good, thanks for the hints!
