### ISSUE TITLE
[Feature request] Send notifications depending on terminal focus

### ISSUE THREAD

**Issue by hardcore-sushi** [ulyssa/iamb#276]
Currently, notifications are not sent if the room is in foreground on the terminal. However, users may still want to receive these notifications in the case their terminal is not visible, for example when using window workspaces or scratchpads. It looks like iamb already knows whether the terminal is focus via the `Application::focused` attribute. Couldn't that be used to decide whether to send a desktop notification?

**Comment by ulyssa** [comment]
Implemented in #281 by @Andrew-Collins
