### ISSUE TITLE
[Feature Request] Package as a Flatpak

### ISSUE THREAD

**Issue by qcsv** [ulyssa/iamb#295]
Packaging Iamb as a Flatpak would make it much more accessible to run on many different Linux distributions and make it easy to sandbox it's permissions with Flatseal.

**Comment by ulyssa** [comment]
Hi @qcsv! I've made a Flatpak for iamb and submitted it to Flathub. You can find it [here](https://flathub.org/apps/chat.iamb.iamb).

**Comment by ulyssa** [comment]
(This should hopefully be a little easier to deal with once I add configuration generation at first startup.)
