### ISSUE TITLE
Off by one cursor placement after copypasting

### ISSUE THREAD

**Issue by drjaska** [ulyssa/iamb#297]
When copypasting text anywhere (tested commands and insert mode) the cursor shifts with the copypaste but it's one character too little.

For example with `|` signifying current cursor position after I have written `hello |` and paste in `iamb` the current text will be `hello iam|b` instead of the correct `hello iamb|`. Continuing to type after this would not insert text after the paste but before the paste's last character which would break any pasted words or links.

Iamb version: the latest git commit, though this is not new issue as I've had this for over a year by now.

OS: Linux / Debian Testing

Terminal: kitty 0.34.1

**Comment by ulyssa** [comment]
I fixed this in ulyssa/modalkit#146. I've updated the `modalkit` dependency to pull it in in #319.
