### ISSUE TITLE
Per Room Notification Settings?

### ISSUE THREAD

**Issue by rmsthebest** [ulyssa/iamb#304]
Hi,
Is it possible to configure the notification options on a per room basis in iamb?

I have some rooms that are important to me, like family chats, and some less important public/group chats I don't want notifications for.

Edit: Looking at the code it looks like iamb already has `RoomNotificationMode`, but only on the notification trigger side. With no way to configuring them. Perhaps it could be added as a room command, "room notification set `<notification level>`"

**Comment by benjajaja** [comment]
In the meantime, it should be possible to configure those settings in another client (e.g. element.io webapp).

**Comment by ulyssa** [comment]
Fixed in #305
