### ISSUE TITLE
Stop overwriting notifications timeout

### ISSUE THREAD

**Issue by freswa** [ulyssa/iamb#313]
[Here](https://github.com/ulyssa/iamb/blob/main/src/notifications.rs#L85) is a hardcoded timeout value set for all notifications. Usually there is a setting in the notification daemon, that handles the duration. Is there any particular reason this is hardcoded and not left to the notification daemon?

**Comment by ulyssa** [comment]
Nope, there isn't a reason. I'm down to remove the timeout and let folk's desktop defaults apply. If it turns out that that lasts too long in some places, then I can add a timeout field to the settings to optionally set one. Thank you for submitting #314!
