### ISSUE TITLE
type annotations needed for `Box<_>`

### ISSUE THREAD

**Issue by alirezaalavi87** [ulyssa/iamb#318]
I get this error when trying to build the app from arch AUR
https://aur.archlinux.org/packages/iamb

rustup: 1.27.1
rustc: 1.80.1

```
error[E0282]: type annotations needed for `Box<_>`
  --> /home/alireza/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.29/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling imbl v2.0.3
   Compiling chacha20poly1305 v0.10.1
   Compiling vodozemac v0.5.1
   Compiling image v0.24.7
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'iamb-0.0.9-1':
error: packages failed to build: iamb-0.0.9-1
```

**Comment by alirezaalavi87** [comment]
sorry for my mistake. the error is from another lib, and I built iamb myself now, and it built successfully. so the problem must be from the PKGBUILD.

**Comment by ulyssa** [comment]
The problem unfortunately comes from a specific version of one the dependencies in the lockfile for v0.0.9 when building with Rust v 1.80 (the latest release). Building from main (which it sounds like is what you ended up doing) or with a Rust version of 1.79 should work.

I'm working towards cutting a new v0.0.10 release which will mean that crates.io then contains a release that builds with 1.80.
