### ISSUE TITLE
iamb is broken on nixos

### ISSUE THREAD

**Issue by just1602** [ulyssa/iamb#331]
Hello :wave: 

Due to the recent rust upgrade on nixos, `iamb` `v0.0.9` is broken since it has a version of the `time` crate that doesn't build with rust 1.80.0. So I was wondering if you plan to cut a new release soon?

Thanks :)

**Comment by ulyssa** [comment]
Hi @just1602 , I've just published and tagged v0.0.10. The package on crates.io now has an updated lockfile, or you can grab a binary from the [Releases](https://github.com/ulyssa/iamb/releases/tag/v0.0.10) until the nixpkgs build is updated to point at the new release.
