### ISSUE TITLE
docs: add example config

### ISSUE THREAD

**Issue by dvdsk** [ulyssa/iamb#354]
Hi there, first off all the docs are great! Its just me that does not really get toml even after many years of working with Cargo.toml's

Could we get an example fully fledged config? Maybe somewhere in the repo and have the docs point to it. I am struggling to figure out `[layout]` etc and seeing a solution would help greatly.

Context what I got stuck on:
```toml
# [layout]
# style = "config"
# tabs = { split = [ { window = ":chats" } , { window = ":chats" } ]}

# [[layout.tabs]]
# split = [
# 	{ split = [ { window = "chats" }, { window = "chats" } ] }
# ]
```

**Comment by dvdsk** [comment]
If anyone can send their fully fledged config I am more then willing to anonymize & annotate it then make a PR adding it as example.

**Comment by ulyssa** [comment]
The [config.example.toml](https://github.com/ulyssa/iamb/blob/v0.0.10/config.example.toml) is meant to be a kind of kitchen sink example and show how to change to a non-default value of every option. Is that close to what you're looking for?

**Comment by dvdsk** [comment]
Oh... I do not see how I missed that...

Thanks for letting me know. I'll put it in the docs in case anyone else is as blind as I was :sweat_smile:
