### ISSUE TITLE
Always opening a new VScode Window

### ISSUE THREAD

**Issue by dedfaf** [ulyssa/iamb#364]
I think this issue is a little bitfunny, so close or ignore it if anyone wish...

I use iamb in the terminal of Windows VSCode and use the `:editor` command to open VSCode for editing messages. However iamb always opens a new VSCode window and a message file tab to edit the messages. It would be much more convenient if I could edit message files in the same VSCode window (just like some people prefer to use VSCode to edit git commit messages).

**Comment by Andrew-Collins** [comment]
Hi @dedfaf,

What platform are you using, and what version of `iamb`?

I'm on linux and using the latest commit on `main` 9a9bdb4, `:editor` will open a tab in an existing `vscode` window, if it exists.

The exact command I ran is `EDITOR=code cargo run -r`.

**Comment by dedfaf** [comment]
@Andrew-Collins 

Windows11, using the iambv0.0.10 release version. and i dont know if iamb could read the `$EDITOR` system value in Windows

I've checked the logs but can't find anything related to this issue..

**Comment by dedfaf** [comment]
Thank for concern@Andrew-Collins 

I'm using Windows 11 with the iamb v0.0.10 release. I'm not sure if iamb can read the `$EDITOR` environment variable on Windows.

I've checked the logs but couldn't find anything related to this issue..

**Comment by dedfaf** [comment]
Thank for concern @Andrew-Collins

I'm using Windows 11 with the iamb v0.0.10 release. I'm not sure if iamb can read the `$EDITOR` environment variable on Windows.

I've checked the logs but couldn't find anything related to this issue..

**Comment by dedfaf** [comment]
it is my fault, iamb is able to read `%EDITOR%` variable on Windows. 

I just modified the `%EDITOR%` value to vim and it works with `vim`, then i modified it back to `code`, and it somehow being able to open the file tab in an already existing vscode window.

However the current problem is, right after opening the file in the correct window, the `.tmpxxx.md` file is soon deleted, i tried created a new file with the same name and save the content of the message, iamb could not read it.

**Comment by dedfaf** [comment]
Log files

[iamb-log-default.2024-10-15.txt](https://github.com/user-attachments/files/17380783/iamb-log-default.2024-10-15.txt)

i run `:editor` command after line 446
