### ISSUE TITLE
[help] [gentoo] Permission denied when creating initial log file

### ISSUE THREAD

**Issue by julie-de-ville** [ulyssa/iamb#365]
Hello,

I just recently switched to gentoo from debian. and I am getting this error:

`initializing rolling file appender failed: InitError { context: "failed to create initial log file", source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }`

As my user, I built the binary using cargo, set permissions to 755, set ownership to 'root', copied the binary to /usr/local/bin

I am using sysklogd for logging, and openrc for init. Help would be appreciated; I have decent linux experience, but I am not used to having to build apps from source as opposed to using package managers.

**Comment by juippis** [comment]
Hey,

there seems to be ebuilds available: https://gpo.zugaina.org/net-im/iamb

You can also easily generate the latest version with **pycargoebuild**:
https://packages.gentoo.org/packages/app-portage/pycargoebuild (help page here https://github.com/projg2/pycargoebuild )

I updated the ebuild locally to 0.0.10 and it seems to work fine installed through package manager.

**Comment by julie-de-ville** [comment]
Thank you, it turned out to be user error actually. I didn't know I had to change the config file for the log directory, so it is working now :)
