### ISSUE TITLE
Decrypt direct messages

### ISSUE THREAD

**Issue by paulcarroty** [ulyssa/iamb#42]
Is it supported now? I got the empty screen.

**Comment by ulyssa** [comment]
Decrypting direct messages is supported. Have you verified the session?

**Comment by paulcarroty** [comment]
@ulyssa the device is verified according to app.element.io and only one message is decrypted successfully. So I believe this is bug.

**Comment by ulyssa** [comment]
If you look at `~/.cache/iamb/logs/` you should be able to find the log messages from the SDK. Are there any `WARN` or `ERROR` messages in there related to decryption?

**Comment by paulcarroty** [comment]
A lot of:
[decrypt.log](https://github.com/ulyssa/iamb/files/10961160/decrypt.log)

**Comment by ulyssa** [comment]
Comparing those logs to where the message is coming from in matrix-sdk-crypto, it looks like you're getting either an `m.room_key` or a `m.forwarded_room_key` with `sender_key` set to `""`. (I'm assuming that `@id:matrix.org` is the sanitized version of your actual username.) I've just added a `"log_level"` field to the `"settings"` object in `config.json`. If you set this to `"debug"`, you should see a message like `"Failed to decrypt a room event, the room key is missing"`.

I believe that synapse just passes along what the other clients send it, so I think that another client is sending it with the empty field. What other clients are you using?

**Comment by paulcarroty** [comment]
I think this is the parser issue 'cause `matrix_sdk_crypto::olm::account: A to-device message was successfully decrypted but parsing and checking the event fields failed`.  Will test `log_level` option later.

> is the sanitized version of your actual username

That's right 😀

> What other clients are you using?

The messages are in gomuks session, after device verification Element Web is able to decrypt all of them successfully.

**Comment by paulcarroty** [comment]
The part of messages now are decrypted successfully. Got the next errors:
[decrypt2.log](https://github.com/ulyssa/iamb/files/11044892/decrypt2.log)

**Comment by k4r4b3y** [comment]
I am also not able to decrypt my DMs from earlier clients. However, from the time I logged into the iamb onwards, it is able to decrypt.

**Comment by k4r4b3y** [comment]
I am taking my comment back. Now iamb is successfully able to decrypt my DMs from earlier clients. Must be a lag on part of the server with keysharing etc.
Sorry for false reporting on my part.
