### ISSUE TITLE
Login fails with cryptic error

### ISSUE THREAD

**Issue by neutralinsomniac** [ulyssa/iamb#53]
Attempting to log into my homeserver pintobyte.com, I get the following:
```
Matrix client error: the server returned an error: EOF while parsing a value at line 1 column 0
```

I can see that I successfully logged in (I have a new device ID and access token), but something seems to be breaking on sync. The only hint I have is in my nginx error log:
```
2023/03/10 16:40:31 [error] 159392#159392: *578750 upstream prematurely closed connection while reading upstream, client: 50.5.223.102, server: pintobyte.com, request: "GET /_matrix/media/r0/thumbnail/zettaport.com/hwueimVHAqYtQGQYQAuiwXaH?width=28&height=28&method=crop HTTP/1.1", upstream: "http://127.0.0.1:8008/_matrix/media/r0/thumbnail/zettaport.com/hwueimVHAqYtQGQYQAuiwXaH?width=28&height=28&method=crop", host: "pintobyte.com:8448"
```

**Comment by neutralinsomniac** [comment]
Additionally, I was able to log in by running iamb on the homeserver itself, connecting to the HTTP port (instead of HTTPS), which is odd but may be a useful data point.

**Comment by ulyssa** [comment]
@neutralinsomniac Do you think could share your nginx config? If I make an unauthenticated request to the sync endpoint on `pintobyte.com`, I get a `405 Method Not Allowed` with an empty body, but when I do it my own homeserver, I get a `401 Unauthorized` with a JSON body:

```
% curl --http1.1 --get -i https://pintobyte.com/_matrix/client/v3/sync
HTTP/1.1 405 Method Not Allowed
Server: nginx/1.22.1
Date: Fri, 10 Mar 2023 23:16:41 GMT
Content-Length: 0
Connection: keep-alive
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Referrer-Policy: origin

% curl --http1.1 --get -i https://0x.badd.cafe/_matrix/client/v3/sync
HTTP/1.1 401 Unauthorized
Server: nginx/1.18.0 (Ubuntu)
Date: Fri, 10 Mar 2023 23:16:51 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Date

{"errcode":"M_MISSING_TOKEN","error":"Missing access token"}
``` 

I wonder if there's a difference in the proxy configuration between the `server` blocks for HTTP and HTTPS.

**Comment by neutralinsomniac** [comment]
Heh you figured it out. I had set up my nginx reverse proxy for the new matrix sliding-sync stuff, and someone in the sliding sync channel had posted a snippet I ended up using where they had that exact endpoint (_matrix/client/v3/sync) forwarding to the sliding sync proxy instead of synapse (which is incorrect). Fixed nginx and now all is good. Thank you!

**Comment by ulyssa** [comment]
I'm glad that you were able to fix it!
