### ISSUE TITLE
No Desktop Notifications on Ubuntu

### ISSUE THREAD

**Issue by neilschuerch** [ulyssa/iamb#69]
I don't receive desktop notifications on Ubuntu 22.

Is this a bug or just not implemented jet?

Otherwise i love it :)

Kind regards

**Comment by aw-bib** [comment]
Maybe a small step could be if `:rooms` gives an `*` if there are unread messages, or even `(nn)` for the number of unread ones.

**Comment by 0323pin** [comment]
@ulyssa sorry for jumping in uninvited but, if you do implement desktop notifications, could this be done as a feature_ that it's possible to disable at compile time?

The reason I ask is that, I find notifications one of the most annoying things, only second to mobile phone vibrations.

**Comment by ulyssa** [comment]
@0323pin I also don't like desktop notifications, so I do plan on having a way to disable it. Is there a reason that you'd prefer a feature over a configuration option?

**Comment by 0323pin** [comment]
A configuration option is fine, thanks!

**Comment by k4r4b3y** [comment]
I would appreciate having the iamb notifications working with `dunst` notification daemon.

**Comment by hardfau18** [comment]
duplicate #116
