### ISSUE TITLE
error: could not compile `iamb`

### ISSUE THREAD

**Issue by 0xblur** [ulyssa/iamb#78]
---
cargo 1.67.1
rustc 1.67.1
---
I get this error when trying to install iamb via .git or directly with cargo:
```
error: could not compile `iamb`

Caused by:
  process didn't exit successfully: `rustc --crate-name iamb --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=f375386580a61b30 -C extra-filename=-f375386580a61b30 --out-dir /home/hadezb/iamb/target/release/deps -L...
```
Then follows a long list of --extern arguments with their respective libraries

**Comment by TornaxO7** [comment]
How do you compile the project? Was it basically
```bash
git clone git@github.com:ulyssa/iamb.git
cd iamb
cargo run
```
?

**Comment by ulyssa** [comment]
@0xblur What operating system are you compiling on? If you're on Linux, you can grab a binary from the [v0.0.7 release](https://github.com/ulyssa/iamb/releases/tag/v0.0.7) page.

It's not clear if this is the cause of the build failure, but how much memory does your system have? I have had rustc get killed on my system before when I've exhausted available memory. You could try turning off optimizations and seeing if that helps to improve things:

```
cargo build --release --config 'profile.release.lto="off"' --config 'profile.release.opt-level=0'
```

**Comment by 0xblur** [comment]
> @0xblur What operating system are you compiling on? If you're on Linux, you can grab a binary from the [v0.0.7 release](https://github.com/ulyssa/iamb/releases/tag/v0.0.7) page.
> 
> It's not clear if this is the cause of the build failure, but how much memory does your system have? I have had rustc get killed on my system before when I've exhausted available memory. You could try turning off optimizations and seeing if that helps to improve things:
> 
> ```
> cargo build --release --config 'profile.release.lto="off"' --config 'profile.release.opt-level=0'
> ```

I will try the binary, and then the build without optimizations. What does turning off optimizations does?

**Comment by ulyssa** [comment]
Turning off optimizations will result in a bigger, unoptimized binary.
