### ISSUE TITLE
blank messages sent if enter/return is pressed while sending a message

### ISSUE THREAD

**Issue by ParkedHampster** [ulyssa/iamb#79]
After hitting enter the first time when a message is sent and before the previous/pending message is removed from the typing viewport, hitting enter again will queue a blank message for each additional time that enter is hit.

**Comment by ulyssa** [comment]
@ParkedHampster What version of iamb are you using? This sounds like #56 which was included in the v0.0.7 release.

**Comment by ParkedHampster** [comment]
I was running on v0.0.6 - it looks like I had installed it through git and thought I had updated everything but hadn't.
Updated to v0.0.7 and it looks like the issue is resolved.
Thank you!
