### ISSUE TITLE
feature suggestion: sort rooms by unread first

### ISSUE THREAD

**Issue by jokeyrhyme** [ulyssa/iamb#83]
Howdie! Thanks for sharing this project!

I'm still getting the hang of it, and Matrix, too, for that matter

Something I miss from the Element Android app is that I'd like rooms with unread messages in them to be sorted to the top of the list in `:rooms` and I suppose have some visual indicator that there are unread messages

If you think this might fit with your vision for `iamb`, I can attempt to raise a PR for it

Cheers!

**Comment by foxyseta** [comment]
Should the (un)read `:rooms`/`:dms` be internally sorted by most recent update time maybe? Element has even settings to customize its own behavior, but I believe this is the default policy?
