### ISSUE TITLE
Respect XDG_CONFIG_DIR on linux

### ISSUE THREAD

**Issue by mpldr** [ulyssa/iamb#86]
It would be nice if iamb used the `XDG_CONFIG_DIR` value (defaults to `~/.config`) to determine where to look for the `iamb/config.json`.

This would allow users to use different configuration directories without requiring creating symbolic links.

**Comment by ulyssa** [comment]
iamb will respect the `XDG_CONFIG_HOME` variable if it's set. There is a `XDG_CONFIG_DIRS` variable, but that is a colon-separated list of paths to search for read-only config files, and defaults to `/etc/xdg`.

**Comment by mpldr** [comment]
Classic case of me misremembering. You are correct.
