### ISSUE TITLE
Move to start/end of word keybindings (`b` and `w`) halt at accented characters

### ISSUE THREAD

**Issue by BeanieBarrow** [ulyssa/iamb#89]
If a word contains an accented character, then pressing `b` or `w` in normal mode only jumps to the character before/after said letter instead of the first or last character of the word.

See this in action on an iconic Hungarian phrase that is used to test programs' and fonts' behavior with accented characters:

https://user-images.githubusercontent.com/105488276/234357203-92d6785c-124e-4039-8ebf-cdfe3d2d9e1a.mp4

A rephrasing of this issue could be that these kinds of special characters get treated as whitespace or punctuation.

**Comment by ulyssa** [comment]
Thank you for reporting this! I've fixed it at ulyssa/modalkit#109 and added the example to the tests. I'm going to cut a modalkit release that includes it, and I'll bump the dependency in iamb.

**Comment by ulyssa** [comment]
I updated to `modalkit@0.0.15` as part of #45 , so I'll mark this as done.
