### ISSUE TITLE
Support marking a room as a direct message room

### ISSUE THREAD

**Issue by ulyssa** [ulyssa/iamb#92]
Matrix has an account-level list of rooms that are direct message rooms, but sometimes some clients don't configure this. Element used to have a way to toggle this, but it looks like it disappeared from the options at some point.

Additionally, Element does seem to have an alternative way to determine whether something appears under the "People" list in its Web and Desktop variants. I should find out how it does this, and see whether I can make iamb do the same thing for placing things under `:dms`.

**Comment by aw-bib** [comment]
> I should find out how it does this

If you happen to find that out I'd be thankful for the insights. Out of sheer curiosity as I don't understand element there, yet ;)

**Comment by ulyssa** [comment]
I still don't know exactly what Element does, but I've added `:room dm set`/`:room dm unset` commands in a98bbd9 for marking a room as DM/non-DM.
