### ISSUE TITLE
Use terminal focus to determine when a message has actually been seen

### ISSUE THREAD

**Issue by BeanieBarrow** [ulyssa/iamb#94]
It has come to my attention that when leaving a room open in my terminal and switching to another window/workspace, any message that gets sent to the room is automatically "seen" by me, even though it isn't.

I don't know if it's possible to check if a terminal gets the focus of the window manager (might be switching stuff up) or not. This bug isn't present when I'm in the room/dm picker menu.

**Comment by ulyssa** [comment]
I've added code to check whether or not the terminal window is focused (for those terminals/multiplexers that support it), and use that to determine whether to update the receipts.
