### ISSUE TITLE
ChatStore::set_receipts locks up app for bad connections

### ISSUE THREAD

**Issue by benjajaja** [ulyssa/iamb#99]
When I disconnect or have a bad connection, then iamb freezes entirely. It accepts no input whatsoever. It resumes normal state when I reconnect.

If I comment out [line 684 in base.rs](https://github.com/ulyssa/iamb/blob/main/src/base.rs#L684):
```rust
let _ = room.read_receipt(read_till.as_ref()).await;
```
then iamb does not freeze at all, because presumably [the lock in the `rcpt_handle` thread](https://github.com/ulyssa/iamb/blob/main/src/worker.rs#L917) is released. Overall, removing that `.await` (or long lock)  makes iamb _feel_ snappier.

Related to #96

**Comment by ulyssa** [comment]
Thanks for tracking this down! I've moved the code that talks to the homeserver out of that method and placed it in the caller instead.

For anyone who doesn't want to build from `main` or wait until the next release for this, setting  `read_receipt_send` to false in your configuration should avoid hitting this specific issue for now.
